; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
src_dir = firmware/src
include_dir = firmware/include
lib_dir = firmware/lib
data_dir = firmware/data
test_dir = firmware/test

[env:seeed_xiao_rp2040]
platform = raspberrypi
board = seeed_xiao_rp2040
framework = arduino

board_build.core = earlephilhower
; board_build.arduino.earlephilhower.usb_vid =
; board_build.arduino.earlephilhower.usb_pid =
; board_build.arduino.earlephilhower.usb_manufacturer =
board_build.arduino.earlephilhower.usb_product = CAD Mouse MK2

build_flags = 
	-DUSE_TINYUSB

lib_deps = 
	infineon/XENSIV 3D Magnetic Sensor TLx493D@^1.1.0
	bxparks/AceButton@^1.10.1
	adafruit/Adafruit NeoPixel@^1.12.3